name: Build Snort3 for ARMv7

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ARM toolchain
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libpcap-dev libpcre3-dev libdnet-dev zlib1g-dev bison flex

    - name: Build Snort3
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++
        make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snort3-armv7
        path: build/src/snort
